{
 "title": "Log Volume - Docker Containers",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Volume by file ($interval interval)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(count_over_time({host=\"docker-desktop\"}[$interval])) by (compose_service)",
     "legendFormat": "{{compose_service}}"
    }
   ]
  },
  {
   "title": "100 Most Recent Log Entries for \"grafana\" Container",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "{host=\"docker-desktop\", compose_service=\"grafana\"}",
     "maxLines": 100
    }
   ]
  },
  {
   "title": "100 Most Recent Log Entries for \"logs\" Container",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "{host=\"docker-desktop\", compose_service=\"logs\"}",
     "maxLines": 100
    }
   ]
  },
  {
   "title": "100 Most Recent Log Entries for \"loki\" Container",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "{host=\"docker-desktop\", compose_service=\"loki\"}",
     "maxLines": 100
    }
   ]
  },
  {
   "title": "100 Most Recent Log Entries for \"promtail\" Container",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "{host=\"docker-desktop\", compose_service=\"promtail\"}",
     "maxLines": 100
    }
   ]
  },
  {
   "title": "100 Most Recent Log Entries for All Containers",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "{host=\"docker-desktop\"}",
     "maxLines": 100
    }
   ]
  }
 ]
}