{
 "title": "Log Volume",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Volume by file ($interval interval)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(count_over_time({host!=\"docker-desktop\",filename=~\"/.*\"}[$interval])) by (filename)",
     "legendFormat": "{{filename}}"
    }
   ]
  },
  {
   "title": "5 Most Recent Synthetic Log Entries",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "{host!=\"docker-desktop\",filename=\"/logs/synthetic/synthetic.log\"}",
     "maxLines": 5
    }
   ]
  },
  {
   "title": "100 Most Recent System Log Entries",
   "type": "logs",
   "description": "This will be empty if you are running on a Mac, as syslog can't be ingested from Docker.  In that case, you'll need to run Promtail locally, as outlined in the README for this project.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "{host!=\"docker-desktop\",filename=\"/var/log/system.log\"}",
     "maxLines": 100
    }
   ]
  },
  {
   "title": "100 Most Recent Log Entries",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "{host!=\"docker-desktop\",filename=~\"/.*\"}",
     "maxLines": 100
    }
   ]
  }
 ]
}