{
 "title": "Promtail Stats",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,5m,10m,15m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Read Bytes Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(promtail_read_bytes_total{job=\"promtail\"}[$interval])",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Read Lines Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "increase(promtail_read_lines_total{job=\"promtail\"}[$interval])",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Files Active Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "promtail_files_active_total{job=\"promtail\"}"
    }
   ]
  },
  {
   "title": "Sent Bytes Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "increase(promtail_sent_bytes_total{job=\"promtail\"}[$interval])"
    }
   ]
  },
  {
   "title": "Sent Entries Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 3, "y": 18 },
   "targets": [
    {
     "expr": "increase(promtail_sent_entries_total{job=\"promtail\"}[$interval])"
    }
   ]
  },
  {
   "title": "Dropped Bytes Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "promtail_dropped_bytes_total{job=\"promtail\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Dropped Bytes Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "promtail_dropped_entries_total{job=\"promtail\"}",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}