{
 "title": "Loki Stats",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,5m,10m,15m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Log Messages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(log_messages_total{job=\"loki\"}[$interval])",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Number of Recevied Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "delta(loki_request_duration_seconds_count{route=\"loki_api_v1_push\"}[$interval])",
     "legendFormat": "Route: {{route}} - {{status_code}}"
    }
   ]
  },
  {
   "title": "Bytes Received",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "delta(loki_distributor_bytes_received_total{job=\"loki\"}[$interval])",
     "legendFormat": "Bytes"
    }
   ]
  },
  {
   "title": "Lines Received",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "delta(loki_distributor_lines_received_total{job=\"loki\"}[$interval])",
     "legendFormat": "Lines"
    }
   ]
  }
 ]
}