{
 "title": "Docker Host Stats (Prometheus)",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,5m,10m,15m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "cpu_usage_user{host=\"telegraf\", cpu=\"cpu-total\"}\n",
     "legendFormat": "{{host}} - CPU User"
    },
    {
     "expr": "cpu_usage_system{cpu=\"cpu-total\"}",
     "legendFormat": "{{host}} - CPU System"
    },
    {
     "expr": "cpu_usage_guest{cpu=\"cpu-total\"}",
     "legendFormat": "{{host}} - CPU Guest"
    },
    {
     "expr": "cpu_usage_iowait{cpu=\"cpu-total\"}",
     "legendFormat": "{{host}} - CPU iowait"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "mem_active{host=\"telegraf\"}",
     "legendFormat": "Active - {{host}}"
    },
    {
     "expr": "mem_cached{host=\"telegraf\"}",
     "legendFormat": "Cached - {{host}}"
    },
    {
     "expr": "mem_shared{host=\"telegraf\"}",
     "legendFormat": "Shared - {{host}}"
    },
    {},
    {}
   ]
  },
  {
   "title": "RAM Available",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "mem_available{host=\"telegraf\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Disk I/O - Read Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(diskio_read_bytes{host=\"telegraf\"}[$interval])",
     "legendFormat": "Read Bytes - {{name}}"
    }
   ]
  },
  {
   "title": "Disk I/O - Write Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(diskio_write_bytes{host=\"telegraf\"}[$interval])",
     "legendFormat": "Write Bytes - {{name}}"
    }
   ]
  }
 ]
}
{
 "title": "Docker Logs",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Volume by file ($interval interval)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(count_over_time({host=\"docker-desktop\"}[$interval])) by (compose_service)",
     "legendFormat": "{{compose_service}}"
    }
   ]
  },
  {
   "title": "100 Most Recent Log Entries for \"grafana\" Container",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "{host=\"docker-desktop\", compose_service=\"grafana\"}",
     "maxLines": 100
    }
   ]
  },
  {
   "title": "100 Most Recent Log Entries for \"logs\" Container",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "{host=\"docker-desktop\", compose_service=\"logs\"}",
     "maxLines": 100
    }
   ]
  },
  {
   "title": "100 Most Recent Log Entries for \"loki\" Container",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "{host=\"docker-desktop\", compose_service=\"loki\"}",
     "maxLines": 100
    }
   ]
  },
  {
   "title": "100 Most Recent Log Entries for \"promtail\" Container",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "{host=\"docker-desktop\", compose_service=\"promtail\"}",
     "maxLines": 100
    }
   ]
  },
  {
   "title": "100 Most Recent Log Entries for All Containers",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "{host=\"docker-desktop\"}",
     "maxLines": 100
    }
   ]
  }
 ]
}
{
 "title": "Loki Stats",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,5m,10m,15m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Log Messages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(log_messages_total{job=\"loki\"}[$interval])",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Number of Recevied Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "delta(loki_request_duration_seconds_count{route=\"loki_api_v1_push\"}[$interval])",
     "legendFormat": "Route: {{route}} - {{status_code}}"
    }
   ]
  },
  {
   "title": "Bytes Received",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "delta(loki_distributor_bytes_received_total{job=\"loki\"}[$interval])",
     "legendFormat": "Bytes"
    }
   ]
  },
  {
   "title": "Lines Received",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "delta(loki_distributor_lines_received_total{job=\"loki\"}[$interval])",
     "legendFormat": "Lines"
    }
   ]
  }
 ]
}
{
 "title": "Ping Results",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "10s,30s,1m,5m,15m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Ping Times ($interval interval)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 23, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(avg_over_time(\n{host=~\".+\", host=\"docker\", filename=~\"/logs/ping/.*\", target!=\"\" } \n|= \"time=\"\n| regexp \"target=(?P<target>[^ ]+)\"\n| regexp \"time=(?P<time>[^ ]+)\"\n| unwrap time\n[$interval]\n)) by (target)\n\n",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Packet Loss - External Hosts ($interval interval)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "avg(avg_over_time(\n{ filename=~\"/logs/ping/.*\", target!=\"\", target!~\"internal-.*\" } \n|= \"transmitted\"\n| logfmt \n| line_format \"pct={{divf .received .transmitted | mulf 100 | sub 100 }}\"\n| logfmt \n| unwrap pct\n| __error__!=\"SampleExtractionErr\"\n[$interval]\n)) \n\n",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Packet Loss by Host - External Hosts ($interval interval)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 23, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "avg(avg_over_time(\n{ filename=~\"/logs/ping/.*\", target != \"\", target!~\"internal-.*\" } \n|= \"transmitted\"\n| logfmt \n| line_format \"pct={{divf .received .transmitted | mulf 100 | sub 100 }}\"\n| logfmt \n| unwrap pct\n| __error__!=\"SampleExtractionErr\"\n[$interval]\n)) by (target)\n\n",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Packet Loss by Host - Internal Host ($interval interval)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 23, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "avg(avg_over_time(\n{ filename=~\"/logs/ping/.*\", target != \"\", target=~\"internal-.*\" } \n|= \"transmitted\"\n| logfmt \n| line_format \"pct={{divf .received .transmitted | mulf 100 | sub 100 }}\"\n| logfmt \n| unwrap pct\n| __error__!=\"SampleExtractionErr\"\n[$interval]\n)) by (target)\n\n",
     "legendFormat": "{{target}}"
    }
   ]
  }
 ]
}
{
 "title": "Ping Results (from Prometheus)",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "30s,1m,5m,15m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Ping Times ($interval interval)",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(ping_sum{type=\"latency\"}[$interval])\n/ rate(ping_count{type=\"latency\"}[$interval])\n",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Packet Loss ($interval interval)",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "rate(ping_sum{type=\"packet_loss\"}[$interval])\n/ rate(ping_count{type=\"packet_loss\"}[$interval])\n",
     "legendFormat": "{{host}}"
    }
   ]
  }
 ]
}
{
 "title": "Promtail Stats",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,5m,10m,15m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Read Bytes Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(promtail_read_bytes_total{job=\"promtail\"}[$interval])",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Read Lines Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "increase(promtail_read_lines_total{job=\"promtail\"}[$interval])",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Files Active Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "promtail_files_active_total{job=\"promtail\"}"
    }
   ]
  },
  {
   "title": "Sent Bytes Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "increase(promtail_sent_bytes_total{job=\"promtail\"}[$interval])"
    }
   ]
  },
  {
   "title": "Sent Entries Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "increase(promtail_sent_entries_total{job=\"promtail\"}[$interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Dropped Bytes Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "promtail_dropped_bytes_total{job=\"promtail\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Dropped Bytes Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "promtail_dropped_entries_total{job=\"promtail\"}",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}
{
 "title": "SEPTA Regional Rail",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "line", "label": "Line: ", "query": "label_values(line)" },
   {
    "name": "interval",
    "query": "1m,5m,15m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Number of Trains by Line",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "expr": "count by (line)\n(\ncount by (line, trainno)\n(\ncount_over_time(\n{job=\"logs-septa\", line=~\"$line\"} | json [$interval]\n)\n)\n)",
     "legendFormat": "{{line}}"
    }
   ]
  },
  {
   "title": "Minutes Late by Line ($line)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "expr": "avg(avg_over_time(\n{job=\"logs-septa\", line=~\"$line\"} \n| json\n| unwrap late\n[$interval]\n)) by (line)",
     "legendFormat": "{{line}}"
    }
   ]
  },
  {
   "title": "Top 10 Latest Trains ($line)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "expr": "topk(10, \navg(avg_over_time(\n{job=\"logs-septa\", line=~\"$line\"} \n| json\n| unwrap late\n[$interval]\n)) by (trainno)\n)",
     "legendFormat": "Train # {{trainno}}"
    }
   ]
  }
 ]
}
{
 "title": "Syslog Volume",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Volume by file ($interval interval)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(count_over_time({host!=\"docker-desktop\",filename=~\"/.*\"}[$interval])) by (filename)",
     "legendFormat": "{{filename}}"
    }
   ]
  },
  {
   "title": "5 Most Recent Synthetic Log Entries",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "{host!=\"docker-desktop\",filename=\"/logs/synthetic/synthetic.log\"}",
     "maxLines": 5
    }
   ]
  },
  {
   "title": "100 Most Recent System Log Entries",
   "type": "logs",
   "description": "This will be empty if you are running on a Mac, as syslog can't be ingested from Docker.  In that case, you'll need to run Promtail locally, as outlined in the README for this project.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "{host!=\"docker-desktop\",filename=\"/var/log/system.log\"}",
     "maxLines": 100
    }
   ]
  },
  {
   "title": "100 Most Recent Log Entries",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "{host!=\"docker-desktop\",filename=~\"/.*\"}",
     "maxLines": 100
    }
   ]
  }
 ]
}