{
 "title": "Log Volume",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Volume by file, 1 minute rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(count_over_time({host!=\"docker-desktop\",filename=~\"/.*\"}[1m])) by (filename)",
     "legendFormat": "{{filename}}"
    }
   ]
  },
  {
   "title": "5 Most Recent Synthetic Log Entries",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "{host!=\"docker-desktop\",filename=\"/logs/synthetic/synthetic.log\"}",
     "maxLines": 5
    }
   ]
  },
  {
   "title": "100 Most Recent System Log Entries",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "{host!=\"docker-desktop\",filename=\"/var/log/system.log\"}",
     "maxLines": 100
    }
   ]
  },
  {
   "title": "100 Most Recent Log Entries",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "{host!=\"docker-desktop\",filename=~\"/.*\"}",
     "maxLines": 100
    }
   ]
  }
 ]
}